spring:
  application:
    name: ACCOUNTING-SERVICE
  kafka:
    consumer:
      group-id: accounting-request-events
      properties:
        spring:
          json:
            trusted:
              packages: by.javaguru.jdmik7.core.command
      bootstrap-servers: localhost:9091,localhost:9092
    producer:
      bootstrap-servers: localhost:9091,localhost:9092
      acks: all
      properties:
        delivery:
          timeout:
            ms: 60000
        linger:
          ms: 0
        request:
          timeout:
            ms: 30000
producer:
  relocation:
    responses:
      topic:
        name: ${RELOCATION_RESPONSES_TOPIC_NAME}
consumer:
  accounting:
    topic:
      name: ${ACCOUNTING_CONSUMER_TOPIC_NAME}

