server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8087/eureka/
  instance:
    prefer-ip-address: true
outbox:
  scheduler:
    pool-size: 3
    interval-ms: 5000
    initial-delay-ms: 0
    initial-offset-ms: 1500
app:
  kafka:
    topics:
      relocation:
        name: ${RELOCATION_TOPIC_NAME}
        partitions: 3
        replicas: 3
        minInSyncReplicas: 2
      accounting:
        name: ${ACCOUNTING_TOPIC_NAME}
        partitions: 3
        replicas: 3
        minInSyncReplicas: 2
      security:
        name: ${SECURITY_TOPIC_NAME}
        partitions: 3
        replicas: 3
        minInSyncReplicas: 2
      notification:
        name: ${NOTIFICATION_TOPIC_NAME}
        partitions: 3
        replicas: 3
        minInSyncReplicas: 2
