server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8087/eureka/
  instance:
    prefer-ip-address: true
app:
  kafka:
    topics:
      relocation:
        name: relocation_responses_events_topic
        partitions: 3
        replicas: 3
        minInSyncReplicas: 2
      accounting:
        name: budget_request_created_events_topic
        partitions: 3
        replicas: 3
        minInSyncReplicas: 2
      security:
        name: security_request_created_events_topic
        partitions: 3
        replicas: 3
        minInSyncReplicas: 2
      notification:
        name: notification_events_topic
        partitions: 3
        replicas: 3
        minInSyncReplicas: 2
