spring:
  application:
    name: NOTIFICATION-SERVICE
  kafka:
    error:
      retry-interval: 3000
      max-attempts: 3
    consumer:
      group-id: notification-request-events
      properties:
        spring:
          json:
            trusted:
              packages: by.javaguru.jdmik7.core.command
      bootstrap-servers: localhost:9091,localhost:9092
