spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/relocation-db
    username: relocation_user
    password: test

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        minimum-number-of-calls: 2
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        event-consumer-buffer-size: 20

  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 10s
        ignore-exceptions:
          - by.javaguru.jdmik7.relocationservice.api.exception.ServiceBadRequestException
