spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 100
        failure-rate-threshold: 30
        minimum-number-of-calls: 20
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 10
        event-consumer-buffer-size: 100

  retry:
    configs:
      default:
        max-attempts: 5
        wait-duration: 5s
        ignore-exceptions:
          - by.javaguru.jdmik7.relocationservice.api.exception.ServiceBadRequestException
