spring:
  kafka:
    consumer:
      group-id: accounting-request-events
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: by.javaguru.jdmik7.core.command
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ""
  liquibase:
    enabled: false

app:
  kafka:
    topics:
      relocation:
        name: "test-relocation-topic"
      accounting:
        name: "test-accounting-topic"
      security: 
        name: "test-security-topic"
      notification:
        name: "test-notification-topic"
