spring:
  application:
    name: RELOCATION-SERVICE
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db.changelog/changelog.xml
app:
  accounting:
    base-url: ${ACCOUNTING_BASE_URL}
  profiler:
    base-url: ${PROFILER_BASE_URL}
  security:
    base-url: ${SECURITY_BASE_URL}
    
logging:
  level:
    by.javaguru.jdmik7.relocationservice: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
management:
  endpoints:
    web:
      exposure:
        include: mapping,bus-refresh,bus-env,circuitbreakerevents,retry
  endpoint:
    health:
      enable: true
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      accounting-service:
        base-config: default
      security-service:
        base-config: default
      profiler-service:
        base-config: default
    circuit-breaker-aspect-order: 1
  retry:
    instances:
      accounting-service:
        base-config: default
      security-service:
        base-config: default
      profiler-service:
        base-config: default
    retry-aspect-order: 2
