spring:
  application:
    name: RELOCATION-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5434/relocation-db
    username: relocation_user
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db.changelog/changelog.xml
